export interface Video {
  id: string;
  title: string;
  description: string;
  thumbnail: string;
  views: string;
  createdAt: string;
  duration: string;
  type?: string;
  creator?: string;
  nickname?: string;
}

export interface Playlist {
  id: string;
  name: string;
  description?: string;
  createdAt: string;
  videos: Video[];
  isPrivate?: boolean;
}

export const videosMock: Video[] = [
  {
    id: '1',
    title: 'Introduction to React Components',
    description: 'Learn the basics of React components.',
    thumbnail: 'https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&w=600&q=80',
    views: '15.4K views',
    createdAt: '2024/1/15',
    duration: '12:45',
    creator: '@alice',
    nickname: '愛麗絲 Alice',
  },
  {
    id: '2',
    title: 'Advanced TypeScript Patterns',
    description: 'Deep dive into TypeScript advanced usage.',
    thumbnail: 'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?auto=format&fit=crop&w=600&q=80',
    views: '8.9K views',
    createdAt: '2024/1/20',
    duration: '18:32',
    creator: '@bob',
    nickname: '小鮑 Bob',
  },
  {
    id: '3',
    title: 'Building Modern UIs with Tailwind',
    description: 'Create beautiful UIs using Tailwind CSS.',
    thumbnail: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=600&q=80',
    views: '12.8K views',
    createdAt: '2024/1/25',
    duration: '25:18',
    creator: '@carol',
    nickname: '凱若 Carol',
  },
  {
    id: '4',
    title: 'State Management Best Practices',
    description: 'How to manage state in large React apps.',
    thumbnail: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=600&q=80',
    views: '6.8K views',
    createdAt: '2024/2/2',
    duration: '22:07',
    creator: '@david',
    nickname: '大衛 David',
  },
  {
    id: '5',
    title: 'API Integration Techniques',
    description: 'Integrate APIs efficiently in your projects.',
    thumbnail: 'https://images.unsplash.com/photo-1465101046530-73398c7f28ca?auto=format&fit=crop&w=600&q=80',
    views: '9.9K views',
    createdAt: '2024/2/5',
    duration: '15:23',
    creator: '@eva',
    nickname: '伊娃 Eva',
  },
  {
    id: '6',
    title: 'Performance Optimization Tips',
    description: 'Tips to optimize your React apps.',
    thumbnail: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=600&q=80',
    views: '11.2K views',
    createdAt: '2024/2/10',
    duration: '19:41',
    creator: '@frank',
    nickname: '法蘭克 Frank',
  },
  {
    id: '7',
    title: '深夜心情（短影音）',
    description: '限時動態短影音內容',
    thumbnail: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=360&q=80',
    views: '2.1K views',
    createdAt: '2024/2/12',
    duration: '24hr',
    type: 'Story',
    creator: '@gina',
    nickname: '吉娜 Gina',
  },
  {
    id: '8',
    title: '夏日泳裝寫真',
    description: '泳裝主題照片',
    thumbnail: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=600&q=80',
    views: '3.2K views',
    createdAt: '2024/2/15',
    duration: '',
    type: 'Photo',
    creator: '@helen',
    nickname: '海倫 Helen',
  },
  {
    id: '9',
    title: 'Next.js 15 實戰技巧',
    description: '深入探討 Next.js 15 的 App Router、Server Actions 與效能調校。',
    thumbnail: 'https://picsum.photos/seed/9/800/450',
    views: '48.3K views',
    createdAt: '2025/3/10',
    duration: '31:22',
    type: 'Video',
    creator: '@nextjspro',
    nickname: '前端達人 Kevin',
  },
  {
    id: '10',
    title: '京都賞櫻 VLOG',
    description: '春季京都四日遊，記錄哲學之道、嵐山與伏見稻荷的滿開盛況。',
    thumbnail: 'https://picsum.photos/seed/10/800/450',
    views: '212.7K views',
    createdAt: '2025/4/2',
    duration: '24:08',
    type: 'Video',
    creator: '@traveljapan',
    nickname: '旅人 Mia',
  },
  {
    id: '11',
    title: '2026 必買科技開箱',
    description: '一次開箱五款 2026 年最熱門的 3C 科技產品，附完整使用心得。',
    thumbnail: 'https://picsum.photos/seed/11/800/450',
    views: '335.1K views',
    createdAt: '2026/1/18',
    duration: '28:55',
    type: 'Video',
    creator: '@techunbox',
    nickname: '開箱王 Jason',
  },
  {
    id: '12',
    title: '極簡主義桌面佈置',
    description: '用不到三千元打造乾淨又有質感的居家工作桌面。',
    thumbnail: 'https://picsum.photos/seed/12/800/450',
    views: '89.6K views',
    createdAt: '2025/9/5',
    duration: '17:44',
    type: 'Video',
    creator: '@minimaldesksetup',
    nickname: '佈置控 Amy',
  },
  {
    id: '13',
    title: '韓式炸雞食譜（短影音）',
    description: '15 分鐘在家做出酥脆韓式炸雞！',
    thumbnail: 'https://picsum.photos/seed/13/800/450',
    views: '500K views',
    createdAt: '2025/11/20',
    duration: '0:58',
    type: 'Story',
    creator: '@foodie_tw',
    nickname: '美食主廚 Leo',
  },
  {
    id: '14',
    title: '夜景街拍｜東京新宿',
    description: '雨夜下的新宿街頭，捕捉霓虹倒影與人群剪影。',
    thumbnail: 'https://picsum.photos/seed/14/800/450',
    views: '62.4K views',
    createdAt: '2025/12/3',
    duration: '',
    type: 'Photo',
    creator: '@streetphoto',
    nickname: '街拍師 Chris',
  },
  {
    id: '15',
    title: '限時動態：健身晨練日常',
    description: '每天早上六點的訓練日常紀錄。',
    thumbnail: 'https://picsum.photos/seed/15/800/450',
    views: '28.9K views',
    createdAt: '2026/2/7',
    duration: '24hr',
    type: 'Highlight',
    creator: '@fitmorning',
    nickname: '健身教練 Max',
  },
  {
    id: '16',
    title: 'React 19 新特性全解析',
    description: '深入解說 React 19 的 use()、Actions 以及全新的編譯器。',
    thumbnail: 'https://picsum.photos/seed/16/800/450',
    views: '71.2K views',
    createdAt: '2025/5/14',
    duration: '36:10',
    type: 'Video',
    creator: '@reactnews',
    nickname: '技術控 Sandy',
  },
  {
    id: '17',
    title: '沖繩五天四夜自由行攻略',
    description: '景點推薦、住宿比較、必吃美食，一支影片全包。',
    thumbnail: 'https://picsum.photos/seed/17/800/450',
    views: '157.8K views',
    createdAt: '2025/7/22',
    duration: '42:33',
    type: 'Video',
    creator: '@okinavlog',
    nickname: '旅遊達人 Nina',
  },
  {
    id: '18',
    title: '30 秒學會 CSS Grid（短影音）',
    description: '用一個超直觀範例秒懂 CSS Grid 排版。',
    thumbnail: 'https://picsum.photos/seed/18/800/450',
    views: '1.2K views',
    createdAt: '2024/8/30',
    duration: '0:32',
    type: 'Story',
    creator: '@cssquick',
    nickname: '前端小教室 Tina',
  },
  {
    id: '19',
    title: '山岳攝影｜合歡山星空',
    description: '一個人上山拍銀河，記錄最美的台灣高山夜空。',
    thumbnail: 'https://picsum.photos/seed/19/800/450',
    views: '43.5K views',
    createdAt: '2024/10/11',
    duration: '',
    type: 'Photo',
    creator: '@milkywayshot',
    nickname: '星空攝影師 Alan',
  },
  {
    id: '20',
    title: '限時動態：咖啡廳選物',
    description: '今天去了一家超美的台北選物咖啡廳。',
    thumbnail: 'https://picsum.photos/seed/20/800/450',
    views: '9.7K views',
    createdAt: '2025/6/19',
    duration: '24hr',
    type: 'Highlight',
    creator: '@cafehunter',
    nickname: '咖啡獵人 Zoe',
  },
  {
    id: '21',
    title: 'AI 工具實測：Cursor vs GitHub Copilot',
    description: '實際用兩款 AI 編碼工具完成同一個專案，比較效率與準確度。',
    thumbnail: 'https://picsum.photos/seed/21/800/450',
    views: '96.4K views',
    createdAt: '2026/3/1',
    duration: '29:47',
    type: 'Video',
    creator: '@aidevtools',
    nickname: 'AI 測評家 Ryan',
  },
  {
    id: '22',
    title: '2025 年度穿搭總回顧',
    description: '整理這一年最愛的 12 套穿搭，附購買連結與搭配邏輯。',
    thumbnail: 'https://picsum.photos/seed/22/800/450',
    views: '183.2K views',
    createdAt: '2025/12/28',
    duration: '21:15',
    type: 'Video',
    creator: '@fashionreview',
    nickname: '時尚編輯 Lily',
  },
  {
    id: '23',
    title: '一鍋到底番茄燉牛肉（短影音）',
    description: '冬天最暖心的料理，步驟簡單新手也能成功。',
    thumbnail: 'https://picsum.photos/seed/23/800/450',
    views: '77.3K views',
    createdAt: '2025/1/8',
    duration: '1:02',
    type: 'Story',
    creator: '@homedish',
    nickname: '家常料理 Tom',
  },
];

// 新增 Highlight 假資料
const highlightMock: Video[] = [
  {
    id: 'h1',
    title: '限時動態：日常隨手拍',
    description: '生活日常的限時動態分享',
    thumbnail: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=360&q=80',
    views: '5.2K views',
    createdAt: '2024/2/18',
    duration: '24hr',
    type: 'Highlight',
  },
  {
    id: 'h2',
    title: '限時動態：旅遊美景',
    description: '旅途中捕捉的美麗瞬間',
    thumbnail: 'https://images.unsplash.com/photo-1508672019048-805c876b67e2?auto=format&fit=crop&w=360&q=80',
    views: '7.8K views',
    createdAt: '2024/2/19',
    duration: '24hr',
    type: 'Highlight',
  },
  {
    id: 'h3',
    title: '限時動態：美食日記',
    description: '分享今日美食',
    thumbnail: 'https://images.unsplash.com/photo-1465101178521-c1a9136a3b99?auto=format&fit=crop&w=360&q=80',
    views: '4.3K views',
    createdAt: '2024/2/20',
    duration: '24hr',
    type: 'Highlight',
  },
];

export const playlistsMock: Playlist[] = [
  {
    id: 'p1',
    name: 'React Fundamentals',
    description: 'Essential React concepts for beginners',
    createdAt: '2024/1/15',
    videos: [
      videosMock[0], videosMock[6], videosMock[7],
      highlightMock[0], highlightMock[1],
      ...videosMock.slice(8),
    ],
  },
  {
    id: 'p2',
    name: 'Advanced Development',
    description: 'Advanced techniques and patterns',
    createdAt: '2024/1/20',
    videos: [videosMock[1], videosMock[3], highlightMock[2]],
  },
  {
    id: 'p3',
    name: 'UI Design & Development',
    description: 'Creating beautiful user interfaces',
    createdAt: '2024/1/25',
    videos: [videosMock[2], videosMock[4], videosMock[5], highlightMock[1]],
  },
]; 